<div>
    {{-- Success/Error Messages (Tailwind/Bootstrap, adjust as needed) --}}
    @if (session()->has('message'))
        <div class="alert alert-success mt-3">
            {{ session('message') }}
        </div>
    @endif
    @if (session()->has('error'))
        <div class="alert alert-danger mt-3">
            {{ session('error') }}
        </div>
    @endif

    <div class="batch-header">
        <div class="breadcrumb">
            <a href="{{ route('history') }}" class="breadcrumb-link">Back to History</a>
            <i class="fas fa-chevron-right breadcrumb-separator"></i>
            <span class="breadcrumb-current">Ticket Batch</span>
        </div>
        <button class="delete-btn" wire:click="$dispatch('open-delete-batch-modal')" style="width:150px !important">
            Delete Batch
        </button>
    </div>

    <div class="batch-summary">
        <div class="summary-row">
            <div class="summary-cell">
                <div class="summary-label">Partner Name</div>
                <div class="summary-value" id="partnerName">{{ $partnerName }}</div>
            </div>
            <div class="summary-cell">
                <div class="summary-label">No. of Tickets</div>
                <div class="summary-value" id="ticketCount">{{ $ticketCount }}</div>
            </div>
            <div class="summary-cell">
                <div class="summary-label">Ticket Type</div>
                <div class="summary-value" id="ticketType">{{ $ticketType }}</div>
            </div>
            <div class="summary-cell">
                <div class="summary-label">Generated By</div>
                <div class="summary-value" id="generatedBy">{{ $generatedBy }}</div>
            </div>
            <div class="summary-cell">
                <div class="summary-label">Price per Ticket</div>
                <div class="summary-value" id="ticketPrice">₦{{ number_format($ticketPrice) }}</div>
            </div>
            <div class="summary-cell">
                <div class="summary-label">Validity Range</div>
                <div class="summary-value" id="validityRange">{{ $validityRange }}</div>
            </div>
        </div>
    </div>

    <div class="all-tickets-section">
        <div class="section-header">
            <h2 class="section-title">All tickets</h2>
            <div class="search-box">
                <i class="fas fa-search search-icon"></i>
                <input type="text" class="search-input" placeholder="search for ticket ID..." wire:model.live.debounce.300ms="search"> {{-- Livewire search with debounce --}}
            </div>
        </div>

        <div class="table-container">
            <table class="tickets-table">
                <thead>
                    <tr>
                        <th>S/N</th>
                        <th>Ticket ID</th>
                        <th class="sortable" wire:click="sortBy('ticket_price')">
                            Price 
                            <i class="fas {{ $this->getSortIcon('ticket_price') }} sort-icon"></i>
                        </th>
                        <th class="sortable" wire:click="sortBy('scanned_by')"> {{-- Logical name for frontend --}}
                            Scanned By 
                            <i class="fas {{ $this->getSortIcon('scanned_by') }} sort-icon"></i>
                        </th>
                        <th class="sortable" wire:click="sortBy('partner_name')"> {{-- Logical name for frontend --}}
                            Partner Name 
                            <i class="fas {{ $this->getSortIcon('partner_name') }} sort-icon"></i>
                        </th>
                        <th class="sortable" wire:click="sortBy('created_at')">
                            Date Generated 
                            <i class="fas {{ $this->getSortIcon('created_at') }} sort-icon"></i>
                        </th>
                        <th class="sortable" wire:click="sortBy('ticket_status')">
                            Status 
                            <i class="fas {{ $this->getSortIcon('ticket_status') }} sort-icon"></i>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($tickets as $ticket)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $ticket->ticket_id }}</td>
                            <td>₦{{ number_format($ticket->ticket_price) }}</td>
                            <td>{{ $ticket->ScannerId->username ?? 'N/A' }}-{{ $ticket->ScannerId->branch ?? 'N/A' }}</td> {{-- Assuming user_id holds name or is linked to user model --}}
                            <td>{{ $ticket->partner->partner_name ?? 'N/A' }}</td>
                            <td>{{ $ticket->created_at->format('M d, Y') }}</td>
                            <td><span class="status-badge status-{{ strtolower($ticket->ticket_status) }}">{{ $ticket->ticket_status }}</span></td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6" class="text-center">No tickets found in this batch matching your criteria.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>

        <div class="mt-4">
            {{ $tickets->links() }} {{-- Livewire's built-in pagination links with Bootstrap theme --}}
        </div>
    </div>

    {{-- Delete Confirmation Modal --}}
    <div class="modal-overlay" id="deleteModal" @if($showDeleteModal) style="display: flex;" @else style="display: none;" @endif>
        <div class="delete-modal">
            <button class="modal-close" wire:click="$dispatch('close-delete-batch-modal')">
                <i class="fas fa-times"></i>
            </button>
            <div class="warning-icon">
                <i class="fas fa-exclamation-triangle"></i>
            </div>
            <h3 class="modal-title">Delete Batch?</h3>
            <p class="modal-message">Are you sure you want to delete this batch (ID: {{ $batchId }})? This action cannot be undone.</p>
            <div class="modal-actions">
                <button class="cancel-btn" wire:click="$dispatch('close-delete-batch-modal')">Cancel</button>
                <button class="confirm-btn" wire:click="deleteBatch">Yes, Delete</button>
            </div>
        </div>
    </div>

    {{-- JavaScript for modal display controlled by Livewire --}}
    <script>
        document.addEventListener('livewire:initialized', () => {
            Livewire.on('open-delete-batch-modal', () => {
                document.getElementById('deleteModal').style.display = 'flex';
            });

            Livewire.on('close-delete-batch-modal', () => {
                document.getElementById('deleteModal').style.display = 'none';
            });
        });
    </script>
</div>